-- From ./hackage-roundtrip-work/ajhc-0.8.0.10/src/Name/Prim.hs

{- WARNING! Do not edit!!!
   This code is autogenerated from src/data/*.txt! -}

{-# Language NoOverloadedStrings #-}
module Name.Prim where

import Name.Name


{-# NOINLINE tc_IOErrorType #-}
tc_IOErrorType = toName TypeConstructor ("Jhc.Type.Handle","IOErrorType")
